name: frederic
description: Ever set a fitness goal and quit halfway through? Frederic keeps you motivated all the way through and helps you build healthy behaviors.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.2+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.7.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_analytics: ^8.3.3
  firebase_messaging: ^10.0.7
  firebase_performance: ^0.7.0+2
  firebase_remote_config: ^0.11.0+1

  google_sign_in: ^5.1.1
  sign_in_with_apple: ^3.2.0
  firebase_app_check: ^0.0.2
  firebase_crashlytics: ^2.2.1
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^9.0.0

  async: ^2.6.1
  crypto: ^3.0.1
  get_it: ^7.1.3
  provider: ^6.0.1
  flutter_bloc: ^7.0.0
  flutter_phoenix: ^1.0.0
  shared_preferences: ^2.0.5
  
  image: ^3.0.2
  lottie: ^1.2.1
  shimmer: ^2.0.0
  confetti: ^0.6.0
  animations: ^2.0.1
  fluttertoast: ^8.0.6
  image_picker: ^0.8.3+2
  url_launcher: ^6.0.6
  cupertino_icons: ^1.0.3
  infinite_listview: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  introduction_screen: ^2.1.0
  cached_network_image: ^3.0.0

  date_format: ^2.0.2

flutter_native_splash:
  background_image: "assets/icon/icon_background.png"
  image: assets/icon/icon_foreground.png
  android_disable_fullscreen: true
  android12: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_ios.png"
  image_path_ios: "assets/icon/icon_ios.png"
  image_path_android: "assets/icon/icon_android.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/dumbbell_with_bg_blue.png
    - assets/images/dumbbell2.png
    - assets/images/login_illustration.png
    - assets/images/Frederic_Goal.png
    - assets/images/introduction_screen_1.png
    - assets/images/introduction_screen_2.png
    - assets/images/introduction_screen_3.png
    - assets/images/google/google_logo_light.png
    - assets/images/Medaille.png
    - assets/animations/app_icon_animation.json

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ExtraIcons
       fonts:
         - asset: assets/fonts/ExtraIcons.ttf
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Medium.ttf
           weight: 500
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
           weight: 900
         - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
           weight: 400
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
           weight: 100
         - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
           weight: 100
           style: italic
