# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: basic_tests

on:
  push:

jobs:
  analyze:
    runs-on: self-hosted

    steps:
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Flutter Setup
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '2.8.0'
    
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .

  unit_test:
    runs-on: self-hosted

    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Flutter Setup
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.8.0'

      - run: flutter pub get
      - run: flutter test














#     - run: flutter build apk
#
#     Upload generated apk to the artifacts.
#    - uses: actions/upload-artifact@v1
#      with:
#        name: release-apk
#        path: build/app/outputs/apk/release/app-release.apk
