name: build_for_android

on:
  workflow_dispatch:
  push:
    tag:
      - "v*.*.*"

jobs:
  build_aab:
    runs-on: ubuntu-latest

    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'
      - run: flutter pub get

      - name: Decrypt keys
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > android/release.keystore.asc
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties.asc
          gpg -d --passphrase "${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSPHRASE }}" --batch android/release.keystore.asc > android/app/release.keystore
          gpg -d --passphrase "${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSPHRASE }}" --batch android/key.properties.asc > android/key.properties

      #      - run: flutter test

      - name: Get Tag name (version code)
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: 'v([0-9]+.[0-9]+.[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Build AAB
        run: flutter build appbundle --release --build-number ${{ steps.date.outputs.date }}01 --build-name ${{ env.GIT_TAG_NAME }}

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          tag: ${{ env.GIT_TAG_NAME }}
          name: APPBUNDLE
          path: build/app/outputs/bundle/release/app-release.aab
